CUDA_VISIBLE_DEVICES=2 python run_ddie.py \
    --task_name MRPC \
    --model_type bert \
    --data_dir /mnt/corpus/test_tsv \
    --model_name_or_path /mnt/model/scibert_scivocab_uncased \
    --per_gpu_train_batch_size 32 \
    --num_train_epochs 3. \
    --dropout_prob .1 \
    --weight_decay .01 \
    --fp16 \
    --do_train \
    --do_eval \
    --do_lower_case \
    --max_seq_length 128 \
    --conv_window_size 5 \
    --pos_emb_dim 10 \
    --activation gelu \
    --middle_layer_size 0 \
    --use_desc \
    --desc_conv_window_size 3 \
    --desc_conv_output_size 20 \
    --molecular_vector_size 50 \
    --gnn_layer_hidden 5 \
    --gnn_layer_output 1 \
    --gnn_mode sum \
    --gnn_activation gelu \
    --fingerprint_dir /mnt/fingerprint/fixed_excluded_radius0 \
    --overwrite_output_dir \
    --output_dir /mnt/DESC_MOL-DDIE/desc/
